# Generated by Django 3.0.8 on 2020-07-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_id', models.PositiveIntegerField(db_column='members_Id', unique=True)),
                ('members_name', models.CharField(db_column='members_Name', max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('admin_flg', models.TextField(db_column='admin_Flg')),
                ('allpayd_days', models.PositiveIntegerField(db_column='allpayd_Days')),
                ('create_date', models.DateTimeField(blank=True, db_column='create_Date', null=True)),
                ('create_by', models.CharField(blank=True, db_column='create_By', max_length=20, null=True)),
                ('update_date', models.DateTimeField(blank=True, db_column='update_Date', null=True)),
                ('update_by', models.CharField(blank=True, db_column='update_By', max_length=20, null=True)),
            ],
            options={
                'db_table': 't_members',
                'managed': False,
            },
        ),
    ]
